databases:
  - name: taklif-db
    databaseName: thmanyah
    plan: free

services:
  # Backend Service
  - type: web
    name: taklif-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    healthCheckPath: /api
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: taklif-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: taklif-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: taklif-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: taklif-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: taklif-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: taklif-db
          property: database

  # Frontend Service
  - type: web
    name: taklif-frontend
    runtime: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_URL
        value: https://taklif-backend-vshl.onrender.com/api
